name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Validate and install Composer dependencies
        run: |
          for dir in . hospital-HR4; do
            if [ -f "$dir/composer.json" ]; then
              cd "$dir"
              composer validate --no-check-publish
              composer install --no-interaction --no-progress --prefer-dist
              cd -
            fi
          done

      - name: PHP syntax check (lint)
        run: |
          set -e
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 -P 4 php -l

  deploy:
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          local-dir: ./
          passive: true
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/*.md
            **/*.bak
            **/*.sql
            **/*.log
